# Generated by Django 5.0.4 on 2024-07-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='instrument',
            field=models.CharField(choices=[('guiter', 'Guiter'), ('drum', 'Drum'), ('amplifire', 'Amplifier')], max_length=30),
        ),
    ]
