# Generated by Django 5.0.4 on 2024-07-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0002_alter_musician_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='instrument',
            field=models.CharField(choices=[('guitar', 'Guitar'), ('drum', 'Drum'), ('amplifier', 'Amplifier')], max_length=30),
        ),
    ]
